name: "analytics_api"
version: "1.0"
profile: "analytics_api"
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  analytics_api:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
